{% set version = "3.1.7-dev" %}

package:
  name: pygna
  version: {{ version | replace("-", "")}}

source:
  path: .

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

  entry_points:
      - pygna = pygna.cli:main

requirements:
  host:
    - python =3.8
    - pip
    - setuptools
    - numpy >=1.16
    - scipy
    - matplotlib
    - pyyaml
    - pytables >=3.4.4
    - seaborn >=0.9
    - palettable
    - networkx ==2.3
    - argh
    - mygene

  run:
    - python =3.8
    - numpy >=1.16
    - scipy
    - matplotlib
    - pyyaml
    - pytables >=3.4.4
    - seaborn >=0.9
    - palettable
    - networkx ==2.3
    - argh
    - mygene

test:
  commands:
    - pygna -h

about:
  home: https://github.com/stracquadaniolab/pygna
  summary: A Python Package for Geneset Network Analysis
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/stracquadaniolab/pygna
  doc_url: https://pygna.readthedocs.io/
  description: |
    PyGNA is a unified framework for network analysis of high-throughput experiments.

extra:
  recipe-maintainers:
    - stracquadaniolab
