FROM python:3.8-slim

# author of file
LABEL maintainer="Fabio Cassano <fabio.cassano@ed.ac.uk>"
LABEL maintainer="Giovanni Stracquadanio <giovanni.stracquadanio@ed.ac.uk>"

# update sources and install tini
RUN apt-get update --fix-missing && apt-get autoremove \
    && apt-get clean \
    && apt-get install tini \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# copy the package and install pygna
WORKDIR /opt
COPY . .
RUN python setup.py install

ENTRYPOINT ["/usr/bin/tini", "--", "pygna"]

