FROM python:3.8-slim

# author of file
LABEL maintainer="Fabio Cassano <fabio.cassano@ed.ac.uk>"

# Packages that we need
COPY requirements.txt /app/
WORKDIR /app

# instruction to be run during image build
RUN python3 -m venv pygna_env
RUN pip install -r requirements.txt

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--", "pygna"]
CMD ["-h"]
