name: "Build"

on:
    push:
        branches:
            - "*"

jobs:
    build:
        name: "Build and test"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [3.8]
                numpy: [1.15]
        steps:
            - uses: actions/checkout@v2

            - name: "Setup Python"
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: "Setup Conda"
              uses: conda-incubator/setup-miniconda@v2
              with:
                  auto-update-conda: true
                  channels: conda-forge,bioconda,defaults
                  conda-build-version: "3.21.7"

            - name: "Install Conda client"
              run: conda install -c anaconda anaconda-client

            - name: "Build Conda package"
              run: |
                  conda build --no-build-id --numpy ${{ matrix.numpy }} --output-folder . .
                  conda convert -p osx-64 linux-64/*.tar.bz2
