name: "Release"

on:
    push:
        tags:
            - "*"

jobs:
    release:
        name: "Build and release"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [3.8]
                numpy: [1.15]
        steps:
            - uses: actions/checkout@v2

            - name: "Setup Python"
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: "Setup Conda"
              uses: conda-incubator/setup-miniconda@v2
              with:
                  auto-update-conda: true
                  channels: conda-forge,bioconda,defaults
                  conda-build-version: "3.21.7"

            - name: "Install Conda client"
              run: conda install -c anaconda anaconda-client

            - name: "Build Conda package"
              run: |
                  conda build --no-build-id --numpy ${{ matrix.numpy }} --output-folder . .
                  conda convert -p osx-64 linux-64/*.tar.bz2

            - name: "Upload Conda package"
              run: |
                  $CONDA/bin/anaconda -t ${{ secrets.ANACONDA_API_TOKEN }} upload --force -u stracquadaniolab --no-progress linux-64/*.tar.bz2
                  $CONDA/bin/anaconda -t ${{ secrets.ANACONDA_API_TOKEN }} upload --force -u stracquadaniolab --no-progress osx-64/*.tar.bz2

            - name: "Login to GitHub Container Registry"
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: "Push Docker image to GitHub Container Registry"
              uses: docker/build-push-action@v2
              with:
                  file: ./docker/Dockerfile
                  push: true
                  tags: ghcr.io/${{ github.repository }}:v3.4.0, ghcr.io/${{ github.repository }}:latest
